export const environment = {
  prod: false,
  apiCategoria: 'https://proyectosno.pythonanywhere.com/api/categorias/',
  apiDetalles: 'https://proyectosno.pythonanywhere.com/api/detallespedidos/',
  apiPedidos: 'https://proyectosno.pythonanywhere.com/api/pedidos/',
  apiProductos: 'https://proyectosno.pythonanywhere.com/api/productos/',
  apiTamaños: 'https://proyectosno.pythonanywhere.com/api/tamanos/',
  apiToppings: 'https://proyectosno.pythonanywhere.com/api/toppings/',
  apiUsuarios: 'https://proyectosno.pythonanywhere.com/api/usuarios/',
  apiProducto_tipo: 'https://proyectosno.pythonanywhere.com/api/productos/por-tipo/',
  apiProducto_categoria: 'https://proyectosno.pythonanywhere.com/api/productos/por-categoria/',
  apiToken: 'https://proyectosno.pythonanywhere.com/token/',
  apiSedes: 'https://proyectosno.pythonanywhere.com/api/sedes/',
  apiTipos: 'https://proyectosno.pythonanywhere.com/api/tipo/',
  apiReset: 'https://proyectosno.pythonanywhere.com/request-reset-email/',
  apiCodigo: 'https://proyectosno.pythonanywhere.com/api/codigo/',
  apiReporteCategoria: 'https://proyectosno.pythonanywhere.com/reporte-ventas-categoria/',
  apiReporteProducto: 'https://proyectosno.pythonanywhere.com/reporte-ventas-producto/',
  apiReporteUsuario: 'https://proyectosno.pythonanywhere.com/reporte-pedidos-usuario/',
};
